### ISSUE TITLE
OS-X 10.10.1 Support? Air16?

### ISSUE THREAD

**Issue by sushihangover** [b005t3r/MacOSFullScreenANE#1]
I'm using OS-X 10.10.1, Air v16, and Apache Flex 4.13.0+ and while I get the following trace output, the Air app never goes full screen. Any ideas? TIA, -X

[trace] [MacOSFullScreen] Initalizing ANE...
[trace] [MacOSFullScreen] ANE initialization complete.
[trace] [MacOSFullScreen] Enabling full screen.

**Comment by b005t3r** [comment]
To switch to full screen you need to click the full screen button on window's frame. On Lion and above is was the symbol located in window's top-right, on Yosemite they changed it into the green dot in the top-left, but for some reason this ANE stopped working also. I didn't check what the problem is, but I encourage you to - the code is simple, it's probably a flag missing, so this should be an easy fix.

**Comment by b005t3r** [comment]
OK, I spent few moments on it, still haven't got a fix (window buttons change they appearance, but the full screen one still just maximizes the window - don't have a clue why), but added a new method - toggleFullScreen() - which works just fine and switches applications window into full screen mode. You just need to call it manually.

It's not a solution, but should work for now.

Here are the changes I made:
ed9f241e3bf7e8bef7ef7bceaffec90a15cc3143
5b5c9ae0eb18b618d1046f4d2233199556d1c8a2
38a5e88fe2096663a1050e51727c39ee32bee33b

**Comment by sushihangover** [comment]
Thanks!

To confirm:
a) The window's stoplight/chrome buttons are displaying correctly now: close, minimize, and full screen (diagonal arrows), but the full screen button activates 'window zoom'. 
b) The new toggleFullScreen() function does cause the app to enter full screen.
c) Exiting full screen via the window's chrome full screen button causes the app to re-size to its previous size but leaves the app in full screen mode.
d) Executing the  toggleFullScreen() function again correctly causes the app to leave full screen mode.

I can work with this for now as at least I can get the air app into its own workspace. (Just adding a Window menu item to exit full screen for now..., not very 'mac'ie', but it will do.). I'll see if I can figure out whats happening later.

Thanks for the quick response and for posting this ANE in the first place(!).

**Comment by b005t3r** [comment]
Thanks for testing it.

I really have no idea why enableFullScreen() doesn't do what it's supposed to do. It's a really basic code, copied from Apple's examples. I'm starting to think that this might be AdobeAIR related bug, maybe it sets some fancy NSApplicationDelegate that blocks windows from going full screen (but shouldn't it block toggleFullScreen calls also)?

**Comment by sushihangover** [comment]
I traced and played with this for a bit and that just left me with the need for a beer, but it does look like the AIR application (container) is doing something strange to the events....

An Adobe AIR bug (3926097) been filed, I'll let you know.
https://bugbase.adobe.com/index.cfm?event=bug&id=3926097

**Comment by b005t3r** [comment]
Thanks for registering this bug with Adobe. I voted on it and shared the link on Starling forum, hopefully it'll get Adobe's attention.

**Comment by b005t3r** [comment]
Overlooked this issue, but this has been fixed for some time now. There's an option to use a workaround on Yosemite.
