### ISSUE TITLE
64-bit problem

### ISSUE THREAD

**Issue by mpress** [b005t3r/MacOSFullScreenANE#2]
Tried out this extension today but got the following error as soon as I tried testing it:

> Process terminated without establishing connection to debugger.
> 
> The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.lazarecki.MacOSFullScreen is not supported for MacOS-x86-64.
> 
> Launch command details:  "/Applications/Adobe Flash Builder 4.7/sdks/4.6.0/bin/adl" -runtime "/Applications/Adobe Flash Builder 4.7/sdks/4.6.0/runtimes/air/mac" -profile extendedDesktop -extdir "/Users/user/Documents/Adobe Flash Builder 4.7/.metadata/.plugins/com.adobe.flexbuilder.project.ui/ANEFiles/FullScreenTest/macosx/" "/Users/user/Documents/Adobe Flash Builder 4.7/FullScreenTest/bin-debug/FullScreenTest-app.xml" "/Users/user/Documents/Adobe Flash Builder 4.7/FullScreenTest/bin-debug"

**Comment by b005t3r** [comment]
This is now resolved, please update to the current version.

**Comment by mpress** [comment]
Thanks very much. That does the job.
