### ISSUE TITLE
[Request] Adapting MacOSFullScreenANE as a wrapper for other independent apps?

### ISSUE THREAD

**Issue by austin-guevara** [b005t3r/MacOSFullScreenANE#4]
Hey people – I don't know if this is the correct place to put a request like this, but maybe you can help me out or point me in the right direction.

I've recently been looking for some sort of script/app that can be used as a "wrapper" so to speak for other Mac apps that don't support native fullscreen mode. Adobe Photoshop CC is the perfect example (wth Adobe?). I just want to be able to use it (and other Adobe CC apps) with native fullscreen mode.

As I'm not truly a developer, what could you tell me about the limitations of adapting this project to create something like that? It feels to me that the functionality isn't particularly complicated.

Is that feasible? What do you think? Thanks!

**Comment by b005t3r** [comment]
I'd like to help, but I have no idea if what you're after is even possible. I'm sure it's not possible with this project, unfortunately.
